### ISSUE TITLE
botV4.py 是不是起不来

### ISSUE THREAD

**Issue by mjyhj** [SuMaiKaDe/jddockerbot#1]
nohup python3 -u /jd/config/botV4.py > /jd/log/botrun.log 2>&1 &

nohup: ignoring input
Traceback (most recent call last):
  File "/jd/config/botV4.py", line 20, in <module>
    bot = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 27 (char 53)

**Comment by SuMaiKaDe** [comment]
看起来是bot.json没有填好，测试了很多，启动还是没有问题的^-^

**Comment by mjyhj** [comment]
> 看起来是bot.json没有填好，测试了很多，启动还是没有问题的^-^

{
    "user_id":93####994,
    "bot_token":151####993:AXXXYA-zAxxxXxqUC_97N9IgrOgkTSyFnfU,
    "api_id":2####27,
    "api_hash":e##ede8a##c51d1af2c######53baa96,
    "proxy":false,
    "proxy_type":, 
    "proxy_add":, 
    "proxy_port":,
    "StartCMD":false
}

**Comment by mjyhj** [comment]
只去掉说明需要去掉的引号，其他保留，起来了

**Comment by ganlu510** [comment]
bot起来了，但是导致docker容器频繁重启

**Comment by SuMaiKaDe** [comment]
> bot起来了，但是导致docker容器频繁重启

日志有吗？使用的谁的docker
