### ISSUE TITLE
/a命令只能使用一个自定义命令

### ISSUE THREAD

**Issue by Wpenga** [SuMaiKaDe/jddockerbot#10]
大佬用/setshort设置自定义命令后，再设置一个原先的就被覆盖了，就只能有一个自定义命令，大佬能否适配可以自定义多个命令。V4和青龙目前都是这样⊙∀⊙！

**Comment by SuMaiKaDe** [comment]
你一次多写几条再发给bot试试，现在是自动覆盖，要不然还要加上删除功能，麻烦。直接按格式编辑config/short.list也行。

**Comment by Wpenga** [comment]
好的，谢谢大佬，这就去试试

**Comment by SuMaiKaDe** [comment]
@Wpenga shortcut.list文件

**Comment by Wpenga** [comment]
可以了，谢谢。
