### ISSUE TITLE
机器人/snode不执行命令

### ISSUE THREAD

**Issue by diamondt5353** [SuMaiKaDe/jddockerbot#11]
我用的是noobx/jd:py镜像，最初的bot.py可以执行

**Comment by SuMaiKaDe** [comment]
@diamondt5353 日志

**Comment by diamondt5353** [comment]
![bot](https://user-images.githubusercontent.com/57979092/115545534-813ea700-a2d6-11eb-887b-f78e8bdd5ae5.PNG)

**Comment by SuMaiKaDe** [comment]
@diamondt5353 问了下镜像作者，说已经不再维护了，建议更换镜像😁

**Comment by diamondt5353** [comment]
![Uploading bot.PNG…]()

**Comment by SuMaiKaDe** [comment]
@diamondt5353 图片打不开

**Comment by diamondt5353** [comment]
那算了吧，我用以前的py文件

**Comment by diamondt5353** [comment]
![bot](https://user-images.githubusercontent.com/57979092/115547523-edbaa580-a2d8-11eb-91c2-8399501e8db0.PNG)

**Comment by diamondt5353** [comment]
![bot11](https://user-images.githubusercontent.com/57979092/115547926-6e79a180-a2d9-11eb-93fd-d04e76e369d0.PNG)

**Comment by diamondt5353** [comment]
这是以前的bot.py文件
