### ISSUE TITLE
希望能支持下自定义命令扩展

### ISSUE THREAD

**Issue by zhaoxiufei** [SuMaiKaDe/jddockerbot#12]
现状: 每次jup就会覆盖自定义的交互.
期望: 增加自定义命令的交互.
如果大佬有时间,可以支持下!谢谢!

**Comment by SuMaiKaDe** [comment]
看不懂

**Comment by zhaoxiufei** [comment]
我在原来的bot.py文件新增加了
@client.on(events.NewMessage(from_users=chat_id, pattern=r'^TA')) 方法
每次执行jup命令都会被覆盖掉,能不能支持下自定义方法的扩展,每次jup的时候不会被覆盖掉

**Comment by SuMaiKaDe** [comment]
@zhaoxiufei 这个我有时间看一下吧

**Comment by zhaoxiufei** [comment]
多谢大佬

**Comment by Wpenga** [comment]
改py脚本是没有用的，因为V4你每次执行jup就会更新机器人的相关文件，因此py文件也会被覆盖到最新的，所以怎么修改py文件都没有用。

**Comment by SuMaiKaDe** [comment]
已更新，支持自定义，放在jbot/diy下边

**Comment by zhaoxiufei** [comment]
感谢大佬 膜拜下 已加星星
