### ISSUE TITLE
bot_token 和 user_id 是哪里获取呢

### ISSUE THREAD

**Issue by UMRQWQ** [SuMaiKaDe/jddockerbot#14]
大佬！
bot_token 和 user_id 是哪里获取呢?
我在https://my.telegram.org/apps创建的bot没有这两个参数呀

**Comment by SuMaiKaDe** [comment]
@UMRQWQ token跟botfather要，user_id是你的tg id

**Comment by UMRQWQ** [comment]
@SuMaiKaDe 我对botfather输入/mybots说我没有bot，我在那个网址创建了，我还要在botfather这里创建吗

**Comment by SuMaiKaDe** [comment]
@UMRQWQ 在botfather创建一个就行了，然后会给你token

**Comment by UMRQWQ** [comment]
@SuMaiKaDe 需要和那个网站中创建的App title还有Short name 这个一样吗？还是随便的名字

**Comment by SuMaiKaDe** [comment]
@UMRQWQ 不需要，随便起名字

**Comment by UMRQWQ** [comment]
@SuMaiKaDe 谢谢，我去试一下

**Comment by UMRQWQ** [comment]
@SuMaiKaDe bot.json中userid需要加双引号吗？

**Comment by SuMaiKaDe** [comment]
看说明
