### ISSUE TITLE
用重启机器人命令，然后现在同时有两个机器人在运行。。

### ISSUE THREAD

**Issue by douzicao** [SuMaiKaDe/jddockerbot#16]
发一条回答2次，这个重启机器人不会杀掉自己吗？

**Comment by SuMaiKaDe** [comment]
@douzicao 你是用的v4bot吗？

**Comment by douzicao** [comment]
> @douzicao 你是用的v4bot吗？

青龙

**Comment by SuMaiKaDe** [comment]
@douzicao 青龙用的rebotql吗

**Comment by douzicao** [comment]
> @douzicao 青龙用的rebotql吗
嗯，不过我已经换了你最新的了，目前还没事。多谢多谢。
