### ISSUE TITLE
青龙机器人

### ISSUE THREAD

**Issue by alililala** [SuMaiKaDe/jddockerbot#17]
青龙开始配置好后能用，然后换了账号后找不到青龙里删除session的地方，导致不能用了。

**Comment by SuMaiKaDe** [comment]
@alililala 在哪个文件夹下运行的脚本，在哪里删除session

**Comment by alililala** [comment]
> @alililala 在哪个文件夹下运行的脚本，在哪里删除session

青龙里边在config文件夹下运行的。找不到删除的地方，不像V4那样在config文件夹下面能看到。

**Comment by SuMaiKaDe** [comment]
@alililala 在docker内运行find / -name bot.session

**Comment by alililala** [comment]
> @alililala 在docker内运行find / -name bot.session

用完也不行，还是启动不了
2021-04-27 23:34:17,993-telethon.network.mtprotosender-INFO=> [_connect] Connecting to 91.108.56.120:443/TcpFull...
2021-04-27 23:34:17,995-telethon.network.mtprotosender-INFO=> [_connect] Connection to 91.108.56.120:443/TcpFull complete!
/usr/lib/python3.8/site-packages/telethon/client/auth.py:153: UserWarning: the session already had an authorized user so it did not login to the bot account using the provided bot_token (it may not be using the user you expect)
  warnings.warn(
