### ISSUE TITLE
pip3 install -r requirements.txt 出现一些错误

### ISSUE THREAD

**Issue by qingyuxiaotian** [SuMaiKaDe/jddockerbot#18]
"value for scheme. purelib does not match" 这种pip3 错误如何解决 pip3.8版本 深度

**Comment by qingyuxiaotian** [comment]
qlbot

**Comment by SuMaiKaDe** [comment]
@qingyuxiaotian 是在docker内执行的吗？

**Comment by qingyuxiaotian** [comment]
是的

**Comment by qingyuxiaotian** [comment]
出现几个scheme. * 相关的包


 packages not  match

**Comment by SuMaiKaDe** [comment]
@qingyuxiaotian 不懂。

**Comment by SuMaiKaDe** [comment]
> 出现几个scheme. * 相关的包
> 
> packages not match

你发一下图片看看，是错误还是警告
