### ISSUE TITLE
希望Bot能够支持编辑文件/edit /jd/config/config.sh

### ISSUE THREAD

**Issue by Wpenga** [SuMaiKaDe/jddockerbot#20]
/edit /jd/config/config.sh
类似这样，不然每次要改类似需要频繁替换的脚本有点繁琐

**Comment by SuMaiKaDe** [comment]
@Wpenga 没看懂

**Comment by Wpenga** [comment]
> /edit /jd/config/config.sh
> 类似这样，可以直接编辑，不然每次要改类似需要频繁替换的脚本需要一个一个文件夹点击并寻找

**Comment by SuMaiKaDe** [comment]
@Wpenga 好

**Comment by Wpenga** [comment]
大佬赛高⊙∀⊙！

**Comment by SuMaiKaDe** [comment]
已更新。
