### ISSUE TITLE
新版的机器人运行以后就会自动下载日志文件，能否修改成返回信息，而不是文件形式

### ISSUE THREAD

**Issue by yyznw** [SuMaiKaDe/jddockerbot#22]
新版的机器人运行以后就会自动下载日志文件，能否修改成返回信息，而不是文件形式

**Comment by SuMaiKaDe** [comment]
@yyznw 你说的是运行什么

**Comment by yyznw** [comment]
通过机器人运行脚本以后，会自动返回此次运行脚本的日志文件，文件的话还得用第三方app打开，能否直接用文字以通知形式返回（虽然和原作者的返回通知信息有重叠）

**Comment by SuMaiKaDe** [comment]
@yyznw tg文字限制4096字符。下次就去了发通知😁

**Comment by SuMaiKaDe** [comment]
> 通过机器人运行脚本以后，会自动返回此次运行脚本的日志文件，文件的话还得用第三方app打开，能否直接用文字以通知形式返回（虽然和原作者的返回通知信息有重叠）

已更新，不超过4096就是文字，超过了发文件
