### ISSUE TITLE
青龙错误

### ISSUE THREAD

**Issue by songshuai0223** [SuMaiKaDe/jddockerbot#23]
![屏幕截图 2021-05-01 232745](https://user-images.githubusercontent.com/58576546/116787125-efece300-aad4-11eb-8e71-bd37a0f3fb01.png)
救救孩子吧 大佬

**Comment by SuMaiKaDe** [comment]
@songshuai0223 不能用？

**Comment by songshuai0223** [comment]
> @songshuai0223 不能用吗？

按照教程搞完 最后一步 就提示这个 。。。。jbot文件夹放在了ql目录下 bot.json 也改了

**Comment by SuMaiKaDe** [comment]
@songshuai0223 看看log/bot/run.log

**Comment by songshuai0223** [comment]
> @songshuai0223 看看log/bot/run.log

![Uploading 9A8ED2EE-7A80-4589-AA50-A9617B542935.jpeg…]()

**Comment by songshuai0223** [comment]
> @songshuai0223 看看log/bot/run.log

![屏幕截图 2021-05-02 071915](https://user-images.githubusercontent.com/58576546/116797286-bb9a1680-ab16-11eb-91a1-56ce78dd8aba.png)

**Comment by SuMaiKaDe** [comment]
后边呢，后边没了吗？你再看看

**Comment by songshuai0223** [comment]
> 后边呢，后边没了吗？你再看看

确定没了 佬 就这三行....

**Comment by SuMaiKaDe** [comment]
你试试这样 nohup python3 -m jbot >/ql/log/bot/bot.log 2&>1 &

**Comment by songshuai0223** [comment]
> nohup python3 -m jbot >/ql/log/bot/bot.log 2&>1 &

![屏幕截图 2021-05-02 073242](https://user-images.githubusercontent.com/58576546/116797476-9e664780-ab18-11eb-80fe-8815c7d3a432.png)

**Comment by songshuai0223** [comment]
> 你试试这样 nohup python3 -m jbot >/ql/log/bot/bot.log 2&>1 &

bot.log里什么都没有... run.log 还是和上边一样的

**Comment by SuMaiKaDe** [comment]
先用ps命令看看后台有没有jbot，有的话杀死 再运行上边那个命令

**Comment by songshuai0223** [comment]
> 先用ps命令看看后台有没有jbot，有的话杀死 再运行上边那个命令

![屏幕截图 2021-05-02 073646](https://user-images.githubusercontent.com/58576546/116797515-2e0bf600-ab19-11eb-9509-2402c7350b43.png)
没有

**Comment by SuMaiKaDe** [comment]
在docker内

**Comment by songshuai0223** [comment]
> 在docker内

![Uploading 屏幕截图 2021-05-02 073835.png…]()

**Comment by songshuai0223** [comment]
> 在docker内

![屏幕截图 2021-05-02 073835](https://user-images.githubusercontent.com/58576546/116797555-77f4dc00-ab19-11eb-8d00-8d50cc5e109e.png)

**Comment by SuMaiKaDe** [comment]
nohup python3 -nm jbot >/ql/log/bot/bot.log 2>&1 &

**Comment by songshuai0223** [comment]
> nohup python3 -nm jbot >/ql/log/bot/bot.log 2>&1 &

![屏幕截图 2021-05-02 074039](https://user-images.githubusercontent.com/58576546/116797575-b7232d00-ab19-11eb-9d96-9b1f5adccd7a.png)
自动出这个

**Comment by songshuai0223** [comment]
![屏幕截图 2021-05-02 074145](https://user-images.githubusercontent.com/58576546/116797593-e0dc5400-ab19-11eb-98bb-727420d53d44.png)
青龙目录下多了这个

**Comment by SuMaiKaDe** [comment]
pip3 install prettytable 但是ql用不了生成bean这个，建议你还是用原来的botql.py吧

**Comment by songshuai0223** [comment]
> pip3 install prettytable 但是ql用不了生成bean这个，建议你还是用原来的botql.py吧

![屏幕截图 2021-05-02 074938](https://user-images.githubusercontent.com/58576546/116797689-04ec6500-ab1b-11eb-8950-e805c0ff1576.png)
还是这样 ， 那我换回去吧。谢谢大佬

**Comment by SuMaiKaDe** [comment]
这是好了吧

**Comment by SuMaiKaDe** [comment]
还是ql吧

**Comment by songshuai0223** [comment]
> 还是ql吧

我继续原来的ql吧 😂 谢谢大佬

**Comment by SuMaiKaDe** [comment]
@songshuai0223 你再试试，更新了一下，我试着没问题

**Comment by songshuai0223** [comment]
![Snipaste_2021-05-07_18-20-01](https://user-images.githubusercontent.com/58576546/117435824-db8b6900-af60-11eb-8359-c9f1bb8900fc.png)
虽然出现这个 但是成功了 大佬牛批！！！！！！！！！！感谢

**Comment by songshuai0223** [comment]
但是好像扫码获取ck又不行了 .....

**Comment by songshuai0223** [comment]
![113](https://user-images.githubusercontent.com/58576546/117436226-55235700-af61-11eb-8714-0f10871a3ac5.png)
这个执行过了

**Comment by songshuai0223** [comment]
/a /edit /getcookie 都不能用  /snode 一直显示正在查询 请稍后

**Comment by SuMaiKaDe** [comment]
@songshuai0223 看看log/bot/run.log

**Comment by songshuai0223** [comment]
> @songshuai0223 看看log/bot/run.log

![5555](https://user-images.githubusercontent.com/58576546/117438866-b4369b00-af64-11eb-8f13-efae3941c313.png)
加载失败了...

**Comment by songshuai0223** [comment]
我重新搞一遍 容器 搞一遍 bot 看看会不会出错

**Comment by songshuai0223** [comment]
![181818](https://user-images.githubusercontent.com/58576546/117440932-49d32a00-af67-11eb-8d1c-3fc34225c8c1.png)
还是一样加载失败 那几个快捷键没法用....

**Comment by SuMaiKaDe** [comment]
@songshuai0223 应该是依赖没装全，先执行apk add那个，再执行pip3 install -r req那个

**Comment by songshuai0223** [comment]
> @songshuai0223 应该是依赖没装全，先执行apk add那个，再执行pip3 install -r req那个

![add](https://user-images.githubusercontent.com/58576546/117442079-e0ecb180-af68-11eb-89cf-0502207e66af.png)
![wwww](https://user-images.githubusercontent.com/58576546/117442088-e2b67500-af68-11eb-931c-984e5fb107dc.png)
没有这个文件啥意思....

**Comment by songshuai0223** [comment]
![35](https://user-images.githubusercontent.com/58576546/117442321-31640f00-af69-11eb-920e-4e3ed4df74fe.png)
jbot一直有这个文件..

**Comment by SuMaiKaDe** [comment]
@songshuai0223 过两天再用吧。。。

**Comment by songshuai0223** [comment]
> @songshuai0223 过两天再用吧。。。

好的

**Comment by SuMaiKaDe** [comment]
@mengdie101 只能使用bean n n代表账户数字
