### ISSUE TITLE
/bean 命令如果遇见有注释的CK会停止，导致后面的CK无法读取。

### ISSUE THREAD

**Issue by wangxin6** [SuMaiKaDe/jddockerbot#25]
config.sh 的设置如下：
<img width="237" alt="image" src="https://user-images.githubusercontent.com/24645789/116838469-0db76680-ac01-11eb-8fcb-878c97595476.png">
/bean 的执行结果：
<img width="335" alt="image" src="https://user-images.githubusercontent.com/24645789/116838495-2a539e80-ac01-11eb-801c-8bdbc108bd75.png">

**Comment by SuMaiKaDe** [comment]
统计是按照日志统计的，跟你config无关
