### ISSUE TITLE
jbot 日志的日期格式与 jlog 不兼容，导致 jlog 不能清理日志

### ISSUE THREAD

**Issue by wangxin6** [SuMaiKaDe/jddockerbot#26]
jbot 日志的日期格式与 jlog 不兼容，导致 jlog 不能清理日志

**Comment by SuMaiKaDe** [comment]
@wangxin6 你说的哪个日志？snode产生的日志吗？如果是的话应该是给你发送完成自动删除的啊。

**Comment by wangxin6** [comment]
run.log 导致的。

<img width="675" alt="image" src="https://user-images.githubusercontent.com/24645789/117088319-bcd07b00-ad84-11eb-8bc5-15e578eb87fd.png">

**Comment by SuMaiKaDe** [comment]
@wangxin6 好的，回头我改一下

**Comment by wangxin6** [comment]
jlog 已更新
