### ISSUE TITLE
E大的V4启动bot报错

### ISSUE THREAD

**Issue by gyq180** [SuMaiKaDe/jddockerbot#27]
[PM2][WARN] Applications jbot not running, starting...
[PM2][ERROR] Error: Script not found: /root/jd/python

我看V4的启动方式是:
cd $JD_DIR/jbot
pm2 start ecosystem.config.js

然后我用在jd或ql目录下运行 nohup python3 -m jbot & 这种方式是可以启动的

**Comment by gyq180** [comment]
还有一个问题,就是目前更新bot是用apk方式更新的, 如果没有用docker而是直装的有更新的办法吗,直装的好像不能用apk

**Comment by SuMaiKaDe** [comment]
@gyq180 用pm2报错吗？这我不太懂。直装更新可以用git吧，定时运行git更新，更新完后用命令或者写个sh杀死原进程，重新启动新进程

**Comment by gyq180** [comment]
已解决,原因是虽然安装了python3,但是python这个命令无法识别,只能识别python3这个命令,下面这行命令可以解决
ln -s /usr/bin/python3.8 /usr/bin/python
