### ISSUE TITLE
运行/snode--选择scripts文件夹显示

### ISSUE THREAD

**Issue by kingsleyzhnlanf** [SuMaiKaDe/jddockerbot#3]
![image](https://user-images.githubusercontent.com/76804516/113469778-f3b02a00-9482-11eb-8f06-26c0255ee42f.png)

**Comment by SuMaiKaDe** [comment]
只是选择scripts文件夹就这样了吗？还是选择下边的文件夹了，然后名字都挺长？

**Comment by kingsleyzhnlanf** [comment]
可能是我用的termux文件路径是/data/data/com.termux/files/home/jd太长了，打开own文件夹时里面的和尚脚本也是这个提示，另一个拉取的库路径/data/data/com.termux/files/home/own/raw倒是可以正常打开

**Comment by nevinee** [comment]
@kingsleyzhnlanf  bot是写死路径的，目前只有docker能用。

**Comment by SuMaiKaDe** [comment]
不是docker是吗？这个没办法，是tg的限制。回头我看看能不能简化一下。

**Comment by kingsleyzhnlanf** [comment]
> 不是docker是吗？这个没办法，是tg的限制。回头我看看能不能简化一下。

不是docker,tg这个限制无语了，可能就多一两个字符
