### ISSUE TITLE
能建立互助码助力池吗？

### ISSUE THREAD

**Issue by cjh19831115** [SuMaiKaDe/jddockerbot#32]
这样功能就能nice了

**Comment by SuMaiKaDe** [comment]
什么互助码互助池？

**Comment by cjh19831115** [comment]
欢迎使用本机器人提交各类活动助力码！

欢迎使用命令 /feedback 向开发者反馈助力池或者机器人的问题，其他问题不回复 
反馈要求：遇到的问题 截图(使用imgurl.org 等其他图床)

/start - 帮助
/register - 注册账户
/submit_activity_codes - 提交各种活动互助码
/get_activities_status - 查询所有活动及上车情况
/feedback - 反馈
/manage_activity - 管理活动(管理员权限)
/ban - 封禁(管理员权限)
/reply - 回复反馈(开发者权限)

助力码每月 1， 8， 16， 24 号凌晨0点清空
同一活动多个助力码请使用批量提交的方式，每周期内每用户同一活动最多提交5个助力码

提交示例：
提交助力码
/submit_activity_codes activity_name sharecode&sharecode （两助力码之间可使用 & @ 两种符号隔开）
查询该活动上车的助力码(此命令会有变动，及时关注)
/force_query_codes activity_name


这是lxk0301机器人建立的互助码助力池，自动取码，互助
