### ISSUE TITLE
bot交互无法运行

### ISSUE THREAD

**Issue by hjyhj-lzz** [SuMaiKaDe/jddockerbot#33]
青龙bot无法用。 输入nohup python3 -m jbot &后nohup: ignoring input and appending output to ‘nohup.out

**Comment by otherbanana** [comment]
同样的问题

**Comment by qpzmalwxmo99** [comment]
我也是nohup: ignoring input and appending output to 'nohup.out'

**Comment by SuMaiKaDe** [comment]
nohup python3 -m jbot >/jd/bot/1.log 2>&1 &
要么就在jbot目录下试试 pm2 start ecosystem.config.js

**Comment by SuMaiKaDe** [comment]
而且青龙用ql bot命令应该就可以启动

**Comment by qpzmalwxmo99** [comment]
OK了，谢谢大佬

SuMaiKaDe ***@***.***> 于2021年5月13日周四 下午1:57写道：
