### ISSUE TITLE
pushplus通知异常

### ISSUE THREAD

**Issue by Qliangw** [SuMaiKaDe/jddockerbot#35]
这个 nevinee/jd 容器，使用pushplus通知出现异常是由于原api接口变更需要更新。

[https://registry.hub.docker.com/r/nevinee/jd](url)

位置位于：/jd/scripts/sendNotify.js中第672行
`const options = {
        url: `http://www.pushplus.plus/send`,
        body: JSON.stringify(body),
        headers: {
          'Content-Type': ' application/json'
        },`
替换为最新的：http://pushplus.hxtrip.com/send即可

**Comment by SuMaiKaDe** [comment]
与本程序无关
