### ISSUE TITLE
本次更新，青龙账号1无法使用chat命令

### ISSUE THREAD

**Issue by yang7758258** [SuMaiKaDe/jddockerbot#37]
![image](https://user-images.githubusercontent.com/43715693/118260164-8ca37d80-b4e4-11eb-98ff-7751c41f4d65.png)

**Comment by SuMaiKaDe** [comment]
jd_bean_change里边有日志吗

**Comment by yang7758258** [comment]
> jd_bean_change里边有日志吗

有日志的，其他账号可以查询

**Comment by yang7758258** [comment]
> jd_bean_change里边有日志吗

是不是范围的问题，1查询不了

**Comment by SuMaiKaDe** [comment]
现在使用的是读取日志，过两天我改成直接从京东获取吧

**Comment by SuMaiKaDe** [comment]
我更新获取数据方式，你试试
