### ISSUE TITLE
/b快捷如何分行显示

### ISSUE THREAD

**Issue by sj1900** [SuMaiKaDe/jddockerbot#41]
设置完/b后只能显示一行12列，超过12个快捷就不显示了，请问如何分多行呢？

**Comment by SuMaiKaDe** [comment]
@sj1900 等更新吧

**Comment by SuMaiKaDe** [comment]
更新了

**Comment by sj1900** [comment]
> 
> 
> 更新了

大佬666！！！
不过有个影响强迫症的地方，最后一个是居中，前面所有都是居上显示。

**Comment by SuMaiKaDe** [comment]
@sj1900 这个以后再说吧

**Comment by sj1900** [comment]
> 
> 
> @sj1900 这个以后再说吧

okok
再次感谢大佬

**Comment by chern91552** [comment]
为什么我/b没反应呢

**Comment by SuMaiKaDe** [comment]
@chern91552 你setshort设置了吗
