### ISSUE TITLE
ql =>JBot加载失败cannot import name 'exceptions'

### ISSUE THREAD

**Issue by ryuurin** [SuMaiKaDe/jddockerbot#43]
![_`@B%WZ$ `ZX2P$X1TD1ZU7](https://user-images.githubusercontent.com/42639499/118358036-9fcf4f80-b5af-11eb-8de4-cbb7ff935ab8.png)
run.log
![IMG_0328](https://user-images.githubusercontent.com/42639499/118358044-a65dc700-b5af-11eb-9ddb-633e45d608e0.PNG)
大部分指令都不行且/snode里面是空的（定时脚本正常运行）

**Comment by SuMaiKaDe** [comment]
依赖安装的不全

**Comment by ryuurin** [comment]
> 依赖安装的不全

docker exec -it qinglong ql bot
我用这个装的，没看到有报错啊

**Comment by ryuurin** [comment]
![image](https://user-images.githubusercontent.com/42639499/118358419-3e0fe500-b5b1-11eb-83d8-70d8763815c7.png)

**Comment by SuMaiKaDe** [comment]
｀pip3 install asyncio｀试试

**Comment by ryuurin** [comment]
> pip3 install asyncio试试

好了！谢谢！
