### ISSUE TITLE
/chart 指令

### ISSUE THREAD

**Issue by yangjun21** [SuMaiKaDe/jddockerbot#44]
都不可以获得图表，请问一下问什么呢？
![屏幕截图 2021-05-15 203416](https://user-images.githubusercontent.com/68324538/118361221-f68f5600-b5bc-11eb-976c-3d508a055e6a.png)
![图片1](https://user-images.githubusercontent.com/68324538/118361222-f727ec80-b5bc-11eb-9abc-92a6ed67c1c4.png)

**Comment by SuMaiKaDe** [comment]
log下边有日志吗

**Comment by yangjun21** [comment]
![5](https://user-images.githubusercontent.com/68324538/118361370-c1cfce80-b5bd-11eb-9e6c-3d73eea6e2a7.png)
这是日志里面的

**Comment by SuMaiKaDe** [comment]
我是说log下边有bean_change那个脚本的日志吗

**Comment by yangjun21** [comment]
![image](https://user-images.githubusercontent.com/68324538/118361784-78807e80-b5bf-11eb-9047-6f2f7648293f.png)
有这个

**Comment by SuMaiKaDe** [comment]
@yangjun21 等有时间了我更新吧

**Comment by yangjun21** [comment]
好的
