### ISSUE TITLE
快捷指令太长，导致出错

### ISSUE THREAD

**Issue by wangxin6** [SuMaiKaDe/jddockerbot#45]
在 shortcut.list 中加入指令后，在 bot 中执行 /a 命令出错
 ‘something wrong,I'm sorry
Too many bytes for the data’

指令如下：
监控关注-->nohup python -u /jd/config/getBean.py >> /jd/log/getBean.log 2>&1 &

**Comment by SuMaiKaDe** [comment]
@wangxin6 所以您有好办法吗？

**Comment by wangxin6** [comment]
那么写个sh吧。谢谢。

**Comment by SuMaiKaDe** [comment]
@wangxin6 写吧
