### ISSUE TITLE
使用/chart命令时，顺序不对

### ISSUE THREAD

**Issue by yongjie9** [SuMaiKaDe/jddockerbot#46]
使用/chart命令时，顺序不对，比如我发送/chart 1，机器人回复的不是第一个ck的收支，而是第6个ck的收支情况

**Comment by SuMaiKaDe** [comment]
V4还是青龙？

**Comment by SuMaiKaDe** [comment]
你是只有6个账号是吗？

**Comment by leiting3986** [comment]
同样的问题，我输入1 出来的9的信息，总共10个账号，输入的2 出来的4的信息，好像没规律

**Comment by SuMaiKaDe** [comment]
@leiting3986 什么环境？

**Comment by leiting3986** [comment]
青龙

> @leiting3986 什么环境？

n1--旁路由--docker--host模式。 青龙 2.0

**Comment by SuMaiKaDe** [comment]
@leiting3986 😂回头我装个青龙看一下吧，可能是读取的文件问题

**Comment by leiting3986** [comment]
> @leiting3986 😂回头我装个青龙看一下吧，可能是读取的文件问题

幸苦了，输入10 来了个6的

**Comment by SuMaiKaDe** [comment]
@leiting3986 青龙cookie.sh文件里ck顺序是正常的吗？

**Comment by leiting3986** [comment]
> @leiting3986 青龙cookie.sh文件里ck顺序是正常的吗？

正常的

**Comment by SuMaiKaDe** [comment]
@leiting3986 😁能打码发一下截图吗？我看看青龙ck是什么格式样式存储的。。。

**Comment by leiting3986** [comment]
![QQ截图20210518111455](https://user-images.githubusercontent.com/22323551/118584837-56a71780-b7ca-11eb-930d-b8c228a4dc18.png)

**Comment by leiting3986** [comment]
![QQ截图20210518111817](https://user-images.githubusercontent.com/22323551/118585094-cd441500-b7ca-11eb-8f4a-cfffb86040de.png)

**Comment by SuMaiKaDe** [comment]
@leiting3986 非常感谢

**Comment by leiting3986** [comment]
> @leiting3986 非常感谢

客气了，谢谢你辛苦了

**Comment by SuMaiKaDe** [comment]
@leiting3986 更新一下试试

**Comment by leiting3986** [comment]
> @leiting3986 更新一下试试

完美，一切正常，多谢
