### ISSUE TITLE
青龙问题

### ISSUE THREAD

**Issue by qiuzhangsaer** [SuMaiKaDe/jddockerbot#48]
现在的bot功能是只有小部分能在青龙正常用吗

**Comment by SuMaiKaDe** [comment]
@qiuzhangsaer 不是啊，都正常啊

**Comment by willinxjf007** [comment]
更新后彻底用不了交互不起来了

**Comment by SuMaiKaDe** [comment]
@willinxjf007 日志

**Comment by willinxjf007** [comment]
nohup: ignoring input
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/ql/jbot/__init__.py", line 1, in <module>
    from telethon import TelegramClient
ModuleNotFoundError: No module named 'telethon'

**Comment by SuMaiKaDe** [comment]
@willinxjf007 没装模块啊 容器内ql bot试试

**Comment by qiuzhangsaer** [comment]
我用青龙的命令安装就有问题，白天手动下载github项目映射目录安装以后可以了，但是开一段时间会自己关闭，不知道是docker后台杀掉了还是自己关了，这个怎么办

**Comment by SuMaiKaDe** [comment]
@qiuzhangsaer 会自己关是什么意思？

**Comment by qiuzhangsaer** [comment]
就是开着开着就不管用了，机器人没反，然后看docker进程,机器人的进程没有了，说白了就是关掉了

**Comment by qiuzhangsaer** [comment]
就是开着开着就不管用了，机器人没反应，然后看docker进程,机器人的进程没有了，说白了就是关掉了

**Comment by SuMaiKaDe** [comment]
@qiuzhangsaer 这个我真不知道，用ql bot命令启动应该是没有问题，对，你设置了容器限制吗？限制内存cpu之类的

**Comment by qiuzhangsaer** [comment]
我是群晖，cpu这些都是用的默认的

**Comment by SuMaiKaDe** [comment]
@qiuzhangsaer 你是自己用命令启动的是吗？不是ql bot

**Comment by qiuzhangsaer** [comment]
对，我是用nohup python3 -m jbot >/dev/null 2>&1 &启动的

**Comment by qiuzhangsaer** [comment]
我发现启动以后进程有三个，一个是python3 -m jbot，一个是timeout 1h nohup python3 -m jbot还有一个bash /usr/local/bin/task nohup python3 -m jbot

**Comment by SuMaiKaDe** [comment]
@qiuzhangsaer 那你用ql bot命令试试，whyour大佬应该是更新了

**Comment by qiuzhangsaer** [comment]
好

**Comment by willinxjf007** [comment]
Requirement already satisfied: pyasn1>=0.1.3 in ./tutorial-env/lib/python3.8/site-packages (from rsa->Telethon==1.21.1->-r requirements.txt (line 2)) (0.4.8)
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 8.2.0
    Uninstalling Pillow-8.2.0:
      Successfully uninstalled Pillow-8.2.0
    Running setup.py install for Pillow ... done
Successfully installed Pillow-8.1.2

python3依赖安装成功...

4、启动bot程序...

mkdir: cannot create directory ‘/ql/log/bot’: File exists
bot启动成功...

/ql/shell/bot.sh: line 37: /ql/log/bot/nohup.log: Not a directory
(tutorial-env) root@QL:/ql $ 

这个是成功了么?我还是没有交互,需要重启么?

**Comment by qiuzhangsaer** [comment]
/bean在青龙上不管用，回调是something wrong,I'm sorry
Command 'jcsv' returned non-zero exit status 127.
还有就是，/cmd有办法发送ctrl+c的操作吗

**Comment by SuMaiKaDe** [comment]
@qiuzhangsaer 没办法，青龙只支持bean 加数字
