### ISSUE TITLE
jbot显示运行 但Telegram上无法交互 重启也无效

### ISSUE THREAD

**Issue by study875** [SuMaiKaDe/jddockerbot#50]
大佬，你好，我这边使用的是 V4-bot 遇到了个问题
![QQ截图20210519095231](https://user-images.githubusercontent.com/53926992/118745033-fb3b5f00-b887-11eb-93b1-7bdb909570fd.jpg)
显示已经在线，但是Telegram无法交互。bot.json这里的都检查设置正确了 因为此前有过交互过的
之前可能是运行 bean.py 脚本没有发现模块，然后安装了一些模块，不知道有没有影响的

**Comment by SuMaiKaDe** [comment]
查看log/bot/run.log日志

**Comment by study875** [comment]
![QQ截图20210519115416](https://user-images.githubusercontent.com/53926992/118754193-1b274e80-b899-11eb-9f30-b17b3d1e02bb.jpg)

发现 log/bot/run.log日志 是空白的 这个是什么问题?

**Comment by SuMaiKaDe** [comment]
@study875 那就是没成功啊，pm2 log看一下

**Comment by study875** [comment]
![QQ截图20210519133523](https://user-images.githubusercontent.com/53926992/118761512-1c5f7800-b8a7-11eb-97f5-ef0e1020480d.jpg)
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lin                         es option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2021-05-19T11:54:08: PM2 log: App [jbot:1] online
PM2        | 2021-05-19T11:54:08: PM2 log: App [jbot:1] exited with code [1] via                          signal [SIGINT]
PM2        | 2021-05-19T11:54:08: PM2 log: App [jbot:1] starting in -fork mode-
PM2        | 2021-05-19T11:54:08: PM2 log: App [jbot:1] online
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] exited with code [1] via                          signal [SIGINT]
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] starting in -fork mode-
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] online
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] exited with code [1] via                          signal [SIGINT]
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] starting in -fork mode-
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] online
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] exited with code [1] via                          signal [SIGINT]
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] starting in -fork mode-
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] online
PM2        | 2021-05-19T11:54:09: PM2 log: App [jbot:1] exited with code [1] via                          signal [SIGINT]
PM2        | 2021-05-19T11:54:09: PM2 log: Script /usr/bin/python had too many u                         nstable restarts (16). Stopped. "errored"

/root/.pm2/logs/jd-crazy-joy-coin-error.log last 15 lines:
/root/.pm2/logs/jbot-out.log last 15 lines:
/root/.pm2/logs/jbot-error.log last 15 lines:
1|jbot     |   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_deta                         ils
1|jbot     |     __import__(pkg_name)
1|jbot     |   File "/jd/jbot/__init__.py", line 1, in <module>
1|jbot     |     from telethon import TelegramClient
1|jbot     | ImportError: cannot import name 'TelegramClient' from 'telethon' (u                         nknown location)
1|jbot     | Traceback (most recent call last):
1|jbot     |   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_m                         ain
1|jbot     |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error                         )
1|jbot     |   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_deta                         ils
1|jbot     |     return _get_module_details(pkg_main_name, error)
1|jbot     |   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_deta                         ils
1|jbot     |     __import__(pkg_name)
1|jbot     |   File "/jd/jbot/__init__.py", line 1, in <module>
1|jbot     |     from telethon import TelegramClient
1|jbot     | ImportError: cannot import name 'TelegramClient' from 'telethon' (unknown location)
                         nknown location)
 这是组件问题吗？ 
![QQ截图20210519133820](https://user-images.githubusercontent.com/53926992/118761737-8710b380-b8a7-11eb-8e82-390fbd9433f9.jpg)

**Comment by SuMaiKaDe** [comment]
@study875 ql吗？

**Comment by study875** [comment]
V4-bot

**Comment by SuMaiKaDe** [comment]
@study875 pip3 install telethon试一下

**Comment by study875** [comment]
![QQ截图20210519141908](https://user-images.githubusercontent.com/53926992/118765142-369c5480-b8ad-11eb-91b9-90f6d28290c2.jpg)
是不是我需要v4-bot重新部署下？

**Comment by SuMaiKaDe** [comment]
@study875 重新部署吧

**Comment by study875** [comment]
好的 谢谢你的帮助了 那我先部署个青龙的看看 青龙可以的话我就用青龙了

**Comment by study875** [comment]
那这个关闭了吧
