### ISSUE TITLE
直接diy bot 发现装不上。。v4普通版本

### ISSUE THREAD

**Issue by 794329041** [SuMaiKaDe/jddockerbot#53]
e大镜像私有了 没法拉取v4 bot 想自己diy安装大佬的bot 结果报错 goole也没啥结果
WARNING: Running pip as root will break packages and permissions. You should ins
tall packages reliably by using venv: https://pip.pypa.io/warnings/venv  
可以帮帮我吗

**Comment by SuMaiKaDe** [comment]
@794329041 这不是报错，忽略即可

**Comment by 794329041** [comment]
> @794329041 这不是报错，忽略即可

谢谢大佬 我再试试

**Comment by 794329041** [comment]
你好 大佬 遇到新问题了 选择/snode 选择scripts 就报错 own就没问题
something wrong,I'm sorry
'utf-8' codec can't decode byte 0xb4 in position 3: invalid start byte
大概是什么情况

**Comment by SuMaiKaDe** [comment]
@794329041 这说明在你的js文件里有一个js文件读取不了，，，

**Comment by 794329041** [comment]
> @794329041 这说明在你的js文件里有一个js文件读取不了，，，

我该如何找到它呢？有一些自己加的js脚本 是它的问题吗

**Comment by SuMaiKaDe** [comment]
@794329041 你看看你加的脚本打开是不是有乱码的，或者看一下保存的编码是不是utf-8

**Comment by 794329041** [comment]
@SuMaiKaDe  感谢大佬 已搞定
