### ISSUE TITLE
nevinee/jd 镜像，bot启动成功但是无法运行镜像

### ISSUE THREAD

**Issue by windforclouds** [SuMaiKaDe/jddockerbot#58]
bot.log显示
nohup: ignoring input
/usr/bin/python3: No module named jbot

pm2 log显示
![image](https://user-images.githubusercontent.com/46742903/119246996-c0ebfd80-bbb8-11eb-8e49-48065de0d15a.png)

**Comment by SuMaiKaDe** [comment]
你这什么方式启动的

**Comment by windforclouds** [comment]
修改了bot.json文件后重启容器然后进入容器内运行jup

**Comment by SuMaiKaDe** [comment]
@windforclouds 什么环境，v4 bot还是v4 是怎么启动的

**Comment by windforclouds** [comment]
> @windforclouds 什么环境，v4 bot还是v4 是怎么启动的
ARMBIAN 5.77 user-built Ubuntu 18.04.4 LTS 5.0.2-aml-s905
v4 bot

**Comment by SuMaiKaDe** [comment]
你设置代理了？

**Comment by windforclouds** [comment]
> 你设置代理了？

嗯嗯对，用了clash

**Comment by SuMaiKaDe** [comment]
@windforclouds json文件看一下来，关键信息打码

**Comment by windforclouds** [comment]
![image](https://user-images.githubusercontent.com/46742903/119247435-f1816680-bbbb-11eb-8db9-2e5c3f782f21.png)

**Comment by SuMaiKaDe** [comment]
add写的不太对应该是，如果是服务器好像需要填写公网ip，但是这样容易被ban，如果是本地🐔跑的写局域网地址，写docker地址行不太通应该是。

**Comment by windforclouds** [comment]
> add写的不太对应该是，如果是服务器好像需要填写公网ip，但是这样容易被ban，如果是本地🐔跑的写局域网地址，写docker地址行不太通应该是。

改成局域网地址还是没成功，是不是这个bot.json还是有问题

**Comment by SuMaiKaDe** [comment]
@windforclouds 端口什么的都写对了吗，日志还是报那个错误吗

**Comment by windforclouds** [comment]
对，都没问题，日志的错误还是跟之前一样；
这个意思是bot没启动成功是吧
![image](https://user-images.githubusercontent.com/46742903/119247785-2f33be80-bbbf-11eb-854c-c323a5056864.png)

**Comment by SuMaiKaDe** [comment]
@windforclouds 这就是网络连不上，你改成socks5类型，把端口也改一下

**Comment by windforclouds** [comment]
> @windforclouds 这就是网络连不上，你改成socks5类型，把端口也改一下

谢谢大佬，这个改好了之后bot通知可以了，代理地址还是要写局域网地址
