### ISSUE TITLE
青龙bot配置好bot后，只要重启docker，bot就没反应了，不知道怎么办

### ISSUE THREAD

**Issue by otis2020** [SuMaiKaDe/jddockerbot#9]
求指导

**Comment by Wpenga** [comment]
需要bash rebotql.sh

**Comment by otis2020** [comment]
> 需要bash rebotql.sh

嗯，只要运行一次rebotql.sh就可以了，但是如果在外出差，家里路由器因为断电或者定时重启了，没法在docker下运行rebot，就没法用bot了，还有没有别的办法，能让docker重启的时候这个rebotql.sh自动运行一下吗？

**Comment by Wpenga** [comment]
bash /ql/config/rebotql.sh
添加定时任务，每两小时或者每5分钟执行一次即可

**Comment by otis2020** [comment]
> bash /ql/config/rebotql.sh
> 添加定时任务，每两小时或者每5分钟执行一次即可

我也想到这个方法了，添加后让每天0：00运行一次，但是我点测试的时候日志里反应好像不对，就是
开始执行...

Sun Apr 18 2021 02:32:59 GMT+0800 (中国标准时间)


执行结束...

这样就结束了

**Comment by otis2020** [comment]
![](https://ftp.bmp.ovh/imgs/2021/04/a00fa688074f81f8.png)

**Comment by SuMaiKaDe** [comment]
可将rebotql.sh内容加入到diy.sh。青龙是叫diy.sh吗？还是ex那个，就是自定义脚本那个。
